### ISSUE TITLE
Error: sqlcipher package is not node-pre-gyp ready

### ISSUE THREAD

**Issue by ua2004** [delaballe/node-sqlcipher#1]
I have Windows 7 x64, Visual Studio 2013. The following error occurs during installation:

    $ npm install https://github.com/delaballe/node-sqlcipher.git

    > sqlcipher@0.0.1 install D:\Node\nw-test\node_modules\sqlcipher
    > node-pre-gyp install --fallback-to-build

    node-pre-gyp ERR! install error
    node-pre-gyp ERR! stack Error: sqlcipher package is not node-pre-gyp ready:
    node-pre-gyp ERR! stack package.json must declare 'binary.remote_uri'
    node-pre-gyp ERR! stack     at validate_config (D:\Node\nw-test\node_modules\sqlcipher\node_modules\node-pre-gyp\lib\util\versioning.js:49:25)
    node-pre-gyp ERR! stack     at Object.module.exports.evaluate (D:\Node\nw-test\node_modules\sqlcipher\node_modules\node-pre-gyp\lib\util\versioning.js:57:5)
    node-pre-gyp ERR! stack     at install (D:\Node\nw-test\node_modules\sqlcipher\node_modules\node-pre-gyp\lib\install.js:120:20)
    node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (D:\Node\nw-test\node_modules\sqlcipher\node_modules\node-pre-gyp\lib\node-pre-gyp.js:50:37)
    node-pre-gyp ERR! stack     at run (D:\Node\nw-test\node_modules\sqlcipher\node_modules\node-pre-gyp\bin\node-pre-gyp:72:30)
    node-pre-gyp ERR! stack     at Object.<anonymous> (D:\Node\nw-test\node_modules\sqlcipher\node_modules\node-pre-gyp\bin\node-pre-gyp:124:1)
    node-pre-gyp ERR! stack     at Module._compile (module.js:541:32)
    node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:550:10)
    node-pre-gyp ERR! stack     at Module.load (module.js:458:32)
    node-pre-gyp ERR! stack     at tryModuleLoad (module.js:417:12)
    node-pre-gyp ERR! System Windows_NT 6.1.7601
    node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Node\\nw-test\\node_modules\\sqlcipher\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd D:\Node\nw-test\node_modules\sqlcipher
    node-pre-gyp ERR! node -v v6.3.0
    node-pre-gyp ERR! node-pre-gyp -v v0.2.6
    node-pre-gyp ERR! not ok

**Comment by delaballe** [comment]
Hi ua2004,

It's nice to see someone interested by the work i've done (a long time ago) i have the same environement at home (Windows 7 x64, Visual Studio 2013.) on which i've successfullly built the lastest NodeJs binary. i'll try to build my old node-sqlcipher on it tomorow. I will keep you in touch !!

**Comment by sijpkes** [comment]
So, did you guys have any luck resolving this? I'm on os x but just need to know this module is stable...

**Comment by mo-js** [comment]
any update?
i need this module for electron

**Comment by chiragkanhasoft** [comment]
any update on this issue ? i want to use this for electron , and i have windows 10
